### ISSUE TITLE
support for quarkus v 2

### ISSUE THREAD

**Issue by lthasle** [quarkiverse/quarkus-logging-json#106]
I tried to use 2.0.0.CR3 and invoked mvn clean install, but go an error.
Are there any plans for upgrading to v2?

Failed to execute goal io.quarkus:quarkus-maven-plugin:2.0.0.CR3:build (default) on project fip-bsf-online: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkiverse.loggingjson.deployment.LoggingJsonProcessor#setUpFormatter threw an exception: java.lang.NoSuchFieldError: JACKSON
[ERROR] 	at io.quarkiverse.loggingjson.deployment.LoggingJsonProcessor.setUpFormatter(LoggingJsonProcessor.java:33)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

**Comment by SlyngDK** [comment]
@lthasle Have you tried with 2.0.0.Final? 
The tests look likes running fine,  and are ready to merge #109.

**Comment by ambition-consulting** [comment]
Same problem, tried it with 2.0.0.Final

[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.0.0.Final:build (default) on project apm-core-app: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkiverse.loggingjson.deployment.LoggingJsonProcessor#setUpFormatter threw an exception: java.lang.NoSuchFieldError: JACKSON
[ERROR] 	at io.quarkiverse.loggingjson.deployment.LoggingJsonProcessor.setUpFormatter(LoggingJsonProcessor.java:33)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]

**Comment by lthasle** [comment]
Thanks! Works fine!

fre. 25. jun. 2021 kl. 19:48 skrev Simon Bengtsson ***@***.***
