### ISSUE TITLE
Support additional json encoders/formatters

### ISSUE THREAD

**Issue by nadworny** [quarkiverse/quarkus-logging-json#132]
I'm trying to implement ECS formatting and haven't found a way to do it using quarkus. [ECS](https://www.elastic.co/guide/en/ecs-logging/java/current/setup.html) is becoming a standard format for many enterprises and I was wondering how difficult it would be to implement it in your plugin?

I was able to format the ExtLogRecord using the ECS library like this but this doesn't replace the whole log entry, it adds a new field:
```java
import co.elastic.logging.jboss.logmanager.EcsFormatter;
import io.quarkiverse.loggingjson.JsonProvider;
import io.quarkiverse.loggingjson.JsonGenerator;
import org.jboss.logmanager.ExtLogRecord;

@Singleton
public class MyJsonProvider implements JsonProvider {

    @Override
    public void writeTo(JsonGenerator generator, ExtLogRecord event) throws IOException {
        var ecsFormatter = new EcsFormatter();
        generator.writeStringField("testingxxx", ecsFormatter.format(event));
    }
}
```

Just add this dependency:
```xml
        <dependency>
            <groupId>co.elastic.logging</groupId>
            <artifactId>jboss-logmanager-ecs-formatter</artifactId>
            <version>1.1.0</version>
        </dependency>
```

Any suggestions?

**Comment by dfa1** [comment]
hello, I had same problem. My solution was simply to disable all of them:

https://github.com/quarkiverse/quarkus-logging-json/issues/105#issuecomment-855274668

Hope it helps!

**Comment by nadworny** [comment]
Thanks but what I need is to replace the whole log statement with the ECS formatter. At the moment I'm only able to add the ECS formatted string as a new field which isn't going to be properly ingested by Elastic.

**Comment by dfa1** [comment]
yes, I had exactly same constraint! 

You can disable everything and you just get a starting {

**Comment by nadworny** [comment]
So if I understood you correctly, when I disable all the fields and write a new field using generator, it should wrap it as a main json? I did the following but it still writes is as a new field and on top of that is also escaping the " in the strings. Here is how it looks:
```json
{"":"{\"@timestamp\":\"2021-09-27T07:43:08.945Z\", \"log.level\": \"INFO\", \"message\":\"Live reload total time: 0.636s \", \"ecs.version\": \"1.2.0\",\"process.thread.name\":\"Timer-0\",\"log.logger\":\"io.quarkus.deployment.dev.RuntimeUpdatesProcessor\"}\n"}
```

Code:
```java
    @Override
    public void writeTo(JsonGenerator generator, ExtLogRecord event) throws IOException {
        var ecsFormatter = new EcsFormatter();
        generator.writeStringField("", ecsFormatter.format(event));
    }
```
Could you please provide a code snippet of how you set it up?

**Comment by dfa1** [comment]
I cannot share my code (it is a custom formatter for another "unfied log format" we have internally in SIX).

But of course you can't do that:

        generator.writeStringField("", ecsFormatter.format(event));

ecsFormatter is giving you a JSON as a string... so you should first parse it back and then "copy" all the content in the generator. 

Otherwise, you could propose a PR in the ECS repository to extend quarkus logging directly.

**Comment by dfa1** [comment]
well, you have several options:

1. parse and copy all keys to the generator. Pseudo-code:
{code}
Json json = Json.parse(ecsFormatter.format(event));
writeToGenerator(generator, key, json)

def writeToGenerator(generator, key, value) {
   if (value instanceof JsonNumber) {
      generator.writeNumber(key, value);
   } else if (value instanceof JsonString) {
     generator.writeString(key, value);
   } else if (value instanceof JsonObject) {
      for (key in keys(value)) {
         writeToGenerator(generator, key, value.get(key))
      }
   } // TODO: handle arrays too
{code}
it could be a bit tricky since it is a recursive algorithm. And it is not very efficient too (since you have to parse JSON and recreate it with another shape). 

2. reimplement the ECS format directly using the generator. You could use `EcsJsonFormatter` as reference:

https://github.com/elastic/ecs-logging-java/blob/fb287cc003ca48cbb9440243b50d79031e2dfa4f/ecs-logging-core/src/main/java/co/elastic/logging/EcsJsonSerializer.java

in both cases you have to disable all providers (like per my original comment).

3. Another option would be to write **a custom quarkus extension** that uses directly the `EcsFormatter` to format the log. Basically providing another implementation of `ExtFormatter`, like this library:

https://github.com/quarkiverse/quarkus-logging-json/blob/master/runtime/src/main/java/io/quarkiverse/loggingjson/JsonFormatter.java

Hope it helps :-) 

PS
In my company we started with option 3. and then switched to option 2. few months back and we are quite happy now (don't have to maintain a custom quarkus extension).

**Comment by dfa1** [comment]
@nadworny you're welcome fellow Zuricher ;)

According to the stacktrace:

           java.lang.RuntimeException: com.fasterxml.jackson.core.JsonGenerationException: Can not start an object, expecting field name (context: Object)
           at io.quarkiverse.loggingjson.JsonFormatter.format(JsonFormatter.java:37)

there is an unexpected JSON object. What is on line 37? Maybe this line?

        generator.writeObject(json);

if so, just use:

       generator.writeObjectFieldStart("log"); // will write "log": {
       generator.writeObjectFieldStart("origin"); // will write "origin": {
       generator.writeObjectFieldStart("file"); // will write "file": {

 
NB
with the generator you can skip "quoting as string" as the generator is safe

**Comment by nadworny** [comment]
Thanks, I'll try it tomorrow.

You mentioned once: 

> Otherwise, you could propose a PR in the ECS repository to extend quarkus logging directly.

Which repository did you mean? Which part of my code do you think I could propose?

**Comment by nadworny** [comment]
It works as suggested, see the updated serializer class.

**Comment by dfa1** [comment]
here: https://github.com/elastic/ecs-logging-java

**Comment by SlyngDK** [comment]
Hi @nadworny @dfa1 

I have released version 1.1.0, with ecs logging format.
```
quarkus.log.console.json.log-format=ecs
```
You are free to test that and give some feedback.

**Comment by nadworny** [comment]
Awesome, I'll test it this week

**Comment by nadworny** [comment]
hey @SlyngDK, it works, thanks a lot!

The only thing I'm missing but it's not a must atm are the "log.origin" and "ecs.version" fields.

**Comment by SlyngDK** [comment]
I have added `ecs.version` in `1.1.1`.
I am not sure about the `log.origin` part.
